const visitRequest: Array<any> = [
  {
    id: 1,
    firstName: "Devjeet",
    lastName: "Roy",
    address: "123/A RMC Lane, Kolkata: 700078",
    gender: "Male",
    profilePic: "/UrbanaAssets/User-Male.jpg",
    profileRating: 8.9,
    phoneNumber: "(+91) 9892882721",
    requestedFor: {
      id: 1,
      name: "Grand Villa",
      carpetArea: 1500,
      configuration: 3,
      furnishingStatus: "Fully Furnished",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus mollitia doloribus quas ea corporis. Libero architecto fuga quas, doloribus quam eos impedit dolores cumque numquam reiciendis aliquam fugiat quos vero?",
      floorPlan: "/UrbanaAssets/floor-plan.jpg",
      brochure: "/doc",
      image: "/SampleHouses/house1.jpg",
      image360: "/Apartments360/a1.jpeg",
      location: "Lords More",
      price: "42,00,000",
      addressLine1: "32 Lords More",
      addressLine2: "Kolkata, West Bengal",
      seller: {
        id: 1,
        firstName: "Devjeet",
        lastName: "Roy",
        address: "123/A RMC Lane, Kolkata: 700078",
        gender: "Male",
        profilePic: "/UrbanaAssets/User-Male.jpg",
        profileRating: 8.9,
        phoneNumber: "(+91) 8332882721",
      },
      city: "Kolkata",
      state: "West bengal",
    },
    visitOn: "23 December, 2022",
    vistStatus: "PENDING",
  },
  {
    id: 2,
    firstName: "Joy",
    lastName: "Saha",
    address: "19/C James Lane, Bangalore: 300078",
    gender: "Male",
    profilePic: "/UrbanaAssets/User-Male.jpg",
    profileRating: 9.3,
    phoneNumber: "(+91) 9892882721",
    requestedFor: {
      id: 3,
      name: "High Towers Villa",
      carpetArea: 1200,
      configuration: 3,
      furnishingStatus: "Semi furnished",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus mollitia doloribus quas ea corporis. Libero architecto fuga quas, doloribus quam eos impedit dolores cumque numquam reiciendis aliquam fugiat quos vero?",
      floorPlan: "/UrbanaAssets/floor-plan.jpg",
      brochure: "/doc",
      image: "/SampleHouses/house3.jpg",
      image360: "/Apartments360/a3.jpeg",
      location: "Mandevilla Gardens",
      price: "1,20,00,000",
      addressLine1: "12 G.P. Lane",
      addressLine2: "Puri, Orissa",
      seller: {
        id: 3,
        firstName: "Meghna",
        lastName: "Adhikary",
        address: "134 CM Lane, Orissa: 500078",
        gender: "Female",
        profilePic: "/UrbanaAssets/User-Female.jpg",
        profileRating: 8.3,
        phoneNumber: "(+91) 7552882721",
      },
      city: "Puri",
      state: "Orissa",
    },
    visitOn: "23 December, 2022",
    vistStatus: "PENDING",
  },
  {
    id: 3,
    firstName: "Meghna",
    lastName: "Adhikary",
    address: "134 CM Lane, Orissa: 500078",
    gender: "Female",
    profilePic: "/UrbanaAssets/User-Female.jpg",
    profileRating: 8.3,
    phoneNumber: "(+91) 9892882721",
    requestedFor: {
      id: 6,
      name: "Kedar Villa",
      carpetArea: 3500,
      configuration: 6,
      furnishingStatus: "Fully Furnished",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus mollitia doloribus quas ea corporis. Libero architecto fuga quas, doloribus quam eos impedit dolores cumque numquam reiciendis aliquam fugiat quos vero?",
      floorPlan: "/UrbanaAssets/floor-plan.jpg",
      brochure: "/doc",
      image: "/SampleHouses/house3.jpg",
      image360: "/Apartments360/a6.jpeg",
      location: "Daringbadi More",
      price: "67,50,000",
      addressLine1: "39 Canal View Road",
      addressLine2: "Daringbadi, Orissa",
      seller: {
        id: 5,
        firstName: "Sneha",
        lastName: "Sen",
        address: "56 Gandhi Sarani, Varanasi: 300078",
        gender: "Female",
        profilePic: "/UrbanaAssets/User-Female.jpg",
        profileRating: 9.6,
        phoneNumber: "(+91) 7773288272",
      },
      city: "Daringbadi",
      state: "Orissa",
    },
    visitOn: "24 December, 2022",
    vistStatus: "PENDING",
  },
  {
    id: 4,
    firstName: "Sneha",
    lastName: "Sen",
    address: "56 Gandhi Sarani, Varanasi: 300078",
    gender: "Female",
    profilePic: "/UrbanaAssets/User-Female.jpg",
    profileRating: 9.6,
    phoneNumber: "(+91) 9892882721",
    requestedFor: {
      id: 4,
      name: "Ram Villa",
      carpetArea: 2500,
      configuration: 5,
      furnishingStatus: "Fully Furnished",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus mollitia doloribus quas ea corporis. Libero architecto fuga quas, doloribus quam eos impedit dolores cumque numquam reiciendis aliquam fugiat quos vero?",
      floorPlan: "/UrbanaAssets/floor-plan.jpg",
      brochure: "/doc",
      image: "/SampleHouses/house4.jpg",
      image360: "/Apartments360/a4.jpeg",
      location: "Esplanade More",
      price: "42,00,000",
      addressLine1: "31/C James Sarani",
      addressLine2: "Jaipur, Rajasthan",
      seller: {
        id: 5,
        firstName: "Sneha",
        lastName: "Sen",
        address: "56 Gandhi Sarani, Varanasi: 300078",
        gender: "Female",
        profilePic: "/UrbanaAssets/User-Female.jpg",
        profileRating: 9.6,
        phoneNumber: "(+91) 8522882721",
      },
      city: "Jaipur",
      state: "Rajasthan",
    },
    visitOn: "24 December, 2022",
    vistStatus: "VISITED",
  },
  {
    id: 3,
    firstName: "Meghna",
    lastName: "Adhikary",
    address: "134 CM Lane, Orissa: 500078",
    gender: "Female",
    profilePic: "/UrbanaAssets/User-Female.jpg",
    profileRating: 8.3,
    phoneNumber: "(+91) 9892882721",
    requestedFor: {
      id: 5,
      name: "Jagannath Villa",
      carpetArea: 2300,
      configuration: 4,
      furnishingStatus: "Unfurnished",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus mollitia doloribus quas ea corporis. Libero architecto fuga quas, doloribus quam eos impedit dolores cumque numquam reiciendis aliquam fugiat quos vero?",
      floorPlan: "/UrbanaAssets/floor-plan.jpg",
      brochure: "/doc",
      image: "/SampleHouses/house1.jpg",
      image360: "/Apartments360/a5.jpeg",
      location: "Daringbadi More",
      price: "92,00,000",
      addressLine1: "31 Canal View Road",
      addressLine2: "Daringbadi, Orissa",
      seller: {
        id: 5,
        firstName: "Sneha",
        lastName: "Sen",
        address: "56 Gandhi Sarani, Varanasi: 300078",
        gender: "Female",
        profilePic: "/UrbanaAssets/User-Female.jpg",
        profileRating: 9.6,
        phoneNumber: "(+91) 7773288272",
      },
      city: "Daringbadi",
      state: "Orissa",
    },
    visitOn: "24 December, 2022",
    vistStatus: "PENDING",
  },
];

export default visitRequest;
